### ISSUE TITLE
hicPlotMatrix not working in develop branch

### ISSUE THREAD

**Issue by fidelram** [deeptools/HiCExplorer#159]
Test command:

```bash
 $ hicPlotMatrix -m test/test_data/Li_et_al_2015.h5 --log1p  -o test_hicPlotMatrix.png
```

Error message:

```
Traceback (most recent call last):
  File "HiCExplorer/bin/hicPlotMatrix", line 7, in <module>
    main()
  File "HiCExplorer/hicexplorer/hicPlotMatrix.py", line 532, in main
    plt.savefig(args.outFileName, dpi=args.dpi)
  File "/lib/python2.7/site-packages/matplotlib/pyplot.py", line 577, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/lib/python2.7/site-packages/matplotlib/figure.py", line 1476, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2211, in print_figure
    **kwargs)
  File "/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    FigureCanvasAgg.draw(self)
  File "/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/lib/python2.7/site-packages/matplotlib/figure.py", line 1085, in draw
    func(*args)
  File "/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2110, in draw
    a.draw(renderer)
  File "/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/lib/python2.7/site-packages/matplotlib/collections.py", line 1797, in draw
    self.update_scalarmappable()
  File "/lib/python2.7/site-packages/matplotlib/collections.py", line 676, in update_scalarmappable
    self._facecolors = self.to_rgba(self._A, self._alpha)
  File "/lib/python2.7/site-packages/matplotlib/cm.py", line 263, in to_rgba
    x = self.cmap(x, alpha=alpha, bytes=bytes)
  File "/lib/python2.7/site-packages/matplotlib/colors.py", line 584, in __call__
    cbook._putmask(xa, xa < 0.0, -1)
RuntimeWarning: invalid value encountered in less
```

if `--region` is used, the command works. 

if --perChr is used, the image looks different compared to version 1.8.1 (left). The tics are missing and there is a white region.:

![image](https://user-images.githubusercontent.com/4964309/34113983-be63d998-e411-11e7-8a65-e9cbcd9e6916.png)

**Comment by joachimwolff** [comment]
I can confirm the missing ticks, the crash if `--log1p` without any additional parameter is used but not the white region in case of `--perChr`.
