### ISSUE TITLE
hicPlotTADs - list of parameters

### ISSUE THREAD

**Issue by samuelCollombet** [deeptools/HiCExplorer#186]
Hi,
Would it be possible to have a list of the possible parameter for the config file (.ini) for hicPlotTADs?
Thanks!

**Comment by gtrichard** [comment]
I think that everything is already covered here:
http://hicexplorer.readthedocs.io/en/latest/content/tools/hicPlotTADs.html#hicplottads

**Comment by samuelCollombet** [comment]
Sorry for example for a hiC, what can be the type (type = interaction in the example; can it be zscore or something else?). I guess that was the main parameter I was wondering about, if all of them are in the example that's perfect :)

**Comment by joachimwolff** [comment]
If you need a good example:
https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/hicPlotTADs.py

**Comment by gtrichard** [comment]
By the way, if you want to plot a z-score matrix, then you can use the .h5 z-score matrices computed by hicFindTADs instead of the corrected Hi-C matrices.

Z-score bedgraph matrices computed by hicFindTADs can also be plotted as [bedgraph matrix] in the .ini file to get an idea of the insulation score at TADs boundaries.

**Comment by samuelCollombet** [comment]
> By the way, if you want to plot a z-score matrix, then you can use the .h5 z-score matrices computed by hicFindTADs instead of the corrected Hi-C matrices.

yes that is what I am trying to do, but I am having some error.

in my config file I wrote:
[hic]
file = TADs/HeardLab_mNPe_HiC_allValidPairs_G2.pairix.cool_zscore_matrix.h5
title = HiC
colormap = RdYlBu_r
depth = 2000000
width = 7
transform = log1p
x labels = yes
type = interaction
file_type = hic_matrix
boundaries_file = TADs/HeardLab_mNPe_HiC_allValidPairs_G2.pairix.cool_boundaries.bed

and when I run hicPlotTADs:

```
 $hicPlotTADs --tracks code_hicExplorer_plotTADs.ini --region chrX:70000000-71000000 -o image.png

INFO:hicexplorer.trackPlot:67.7989749908
INFO:hicexplorer.trackPlot:setting min, max values for track 1. [hic] to: 0.783548971498, 1.59572344311

Traceback (most recent call last):
  File "/usr/local/src/anaconda2/bin/hicPlotTADs", line 7, in <module>
    main()
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/hicexplorer/hicPlotTADs.py", line 365, in main
    trp.plot(args.outFileName, *region, title=args.title)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/hicexplorer/trackPlot.py", line 238, in plot
    fig.savefig(file_name, dpi=self.dpi, transparent=False)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2267, in print_figure
    **kwargs)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 507, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1299, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/mpl_toolkits/axisartist/axislines.py", line 777, in draw
    super(Axes, self).draw(renderer, inframe)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2437, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/collections.py", line 1890, in draw
    self.update_scalarmappable()
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/collections.py", line 759, in update_scalarmappable
    self._facecolors = self.to_rgba(self._A, self._alpha)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/cm.py", line 275, in to_rgba
    x = self.norm(x)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/matplotlib/colors.py", line 1012, in __call__
    mask |= resdat <= 0
RuntimeWarning: invalid value encountered in less_equal
```
Any idea?
Thanks!

**Comment by gtrichard** [comment]
I think that is because you are using a `_boundaries.bed` instead of a `_domains.bed` file for the `boundaries_file =` parameter.

Perhaps a renaming of `boundaries_file` to `domains_file` would be less confusing @joachimwolff @fidelram ?

**Comment by samuelCollombet** [comment]
> I think that is because you are using a _boundaries.bed instead of a _domains.bed file for the boundaries_file = parameter.
I am afraid not, I changed the parameter and get the same error :/ 

I am using a .cool matrix, maybe there is a problem there? I can send you the file to test.

**Comment by fidelram** [comment]
quick question: If you only plot the matrix without the boundaries, does it works?

**Comment by samuelCollombet** [comment]
Sorry my bad: I left the argument "transform = log1p" which for the zscore must give some problem with negative values... Sorry!
