### ISSUE TITLE
hicPlotTADs error with numpy >1.9.3

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#199]
Hello,

I installed the **documentation branch** locally on one OSX and one Linux machine, and both have the following bug when using hicPlotTADs:

```
hicPlotTADs --help
Traceback (most recent call last):
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/bin/hicPlotTADs", line 4, in <module>
    from hicexplorer.hicPlotTADs import main
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/hicexplorer/hicPlotTADs.py", line 190, in <module>
    import hicexplorer.trackPlot
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/hicexplorer/trackPlot.py", line 36, in <module>
    import scipy.sparse
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/scipy/sparse/__init__.py", line 231, in <module>
    from .lil import *
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/scipy/sparse/lil.py", line 16, in <module>
    from . import _csparsetools
  File "__init__.pxd", line 155, in init scipy.sparse._csparsetools
RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
```

I uninstalled and installed multiple version of numpy and with numpy 1.9.3 for example `hicPlotTADs --help` was then working. After a `pip install --upgrade numpy`, I get the error message once again. Installing a more recent version than 1.9.3 like 1.10.0 also throws the error described above.

**Comment by joachimwolff** [comment]
In my experience this looks like a conflict of numpy and scipy versions on your machine. Usually you have to delete files in .local or so which are related to numpy and python. Maybe just ask someone with experience in Python troubleshooting at the MPI, I spend hours of my life resolving this stuff.

**Comment by gtrichard** [comment]
Ah I always installed HiCExplorer with pip... Thanks for the info, I'll try a conda installation then.

Hum let me try a clean installation of this branch of HiCExplorer in a new virtual environment, just to be sure that the branch is working out of the box (it should according to Travis CI).
