### ISSUE TITLE
Please checkthe correct spelling of the chromosome names.

### ISSUE THREAD

**Issue by mictadlo** [deeptools/HiCExplorer#273]
Hi,
I have a denovo assembly I tried to run HiCExplorer in order to get 19 chromosome bins. Unfortunately, I got the following error:

```
WARNING:hicexplorer.hicPlotMatrix:WARNING: The following chromosome/scaffold names were not found. Please checkthe correct spelling of the chromosome names. 

WARNING:hicexplorer.hicPlotMatrix:chr1
chr2
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/bin/hicPlotMatrix", line 7, in <module>
    main()
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/hicPlotMatrix.py", line 517, in main
    ma.reorderChromosomes(valid_chromosomes)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 1591, in reorderChromosomes
    self.reorderBins(new_order)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 1616, in reorderBins
    self.intervalListToIntervalTree(self.cut_intervals)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 1948, in intervalListToIntervalTree
    assert len(interval_list) > 0, "Interval list is empty"
AssertionError: Interval list is empty
Chromosome name 'chr1' not found. Please check the correct spelling of the chromosomes and try again
Chromosome name 'chr1' not found. Please check the correct spelling of the chromosomes and try again
Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/bin/hicPlotMatrix", line 7, in <module>
    main()
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/hicPlotMatrix.py", line 494, in main
    ma = HiCMatrix.hiCMatrix(args.matrix)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 84, in __init__
    hiCMatrix.load_h5(matrixFile)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 233, in load_h5
    with tables.open_file(matrix_filename) as f:
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 371, in tables.hdf5extension.File._g_new
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/tables/utils.py", line 157, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
IOError: ``hic/replicateMerged.Corrected_20kb.h5`` does not exist
Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/bin/hicFindTADs", line 7, in <module>
    main()
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py", line 1318, in main
    p_correct_for_multiple_testing=args.correctForMultipleTesting, p_threshold_comparisons=args.thresholdComparisons)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py", line 379, in __init__
    self.hic_ma = hm.hiCMatrix(matrix)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 84, in __init__
    hiCMatrix.load_h5(matrixFile)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 233, in load_h5
    with tables.open_file(matrix_filename) as f:
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 371, in tables.hdf5extension.File._g_new
  File "/work/waterhouse_team/miniconda2/envs/hicexplorer/lib/python2.7/site-packages/tables/utils.py", line 157, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
IOError: ``hic/replicateMerged.Corrected_20kb.h5`` does not exist
```

I used the following commands:
```
hicSumMatrices \
--matrices hic/N_Ben_HiC2..fq.gz.bam-hic_matrix.h5  hic/N_Ben_HiC4..fq.gz.bam-hic_matrix.h5  \
--outFileName hic/replicateMerged.h5

hicMergeMatrixBins \
--matrix hic/replicateMerged.h5 --numBins 100 \
--outFileName hic/replicateMerged.100bins.h5

hicPlotMatrix \
--matrix hic/replicateMerged.100bins.h5 \
--log1p \
--dpi 300 \
--clearMaskedBins \
--chromosomeOrder chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 \
--colorMap jet \
--title "Hi-C matrix" \
--outFileName hic/plot_1Mb_matrix.png

hicMergeMatrixBins \
--matrix hic/replicateMerged.h5 --numBins 2 \
--outFileName hic/replicateMerged.matrix_20kb.h5

hicCorrectMatrix diagnostic_plot \
--chromosomes chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 \
--matrix hic/replicateMerged.matrix_20kb.h5 --plotName hic/diagnostic_plot.png

hicCorrectMatrix correct \
--chromosomes chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 \
--matrix hic/replicateMerged.matrix_20kb.h5 \
--filterThreshold -2 3 --perchr --outFileName hic/replicateMerged.Corrected_20kb.h5

hicPlotMatrix \
--matrix hic/replicateMerged.Corrected_20kb.h5 \
--log1p \
--dpi 300 \
--clearMaskedBins \
--chromosomeOrder chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 \
--colorMap jet \
--title "Corrected Hi-C matrix" \
--outFileName hic/plot_1Mb_corrected_matrix.png

hicFindTADs --matrix hic/replicateMerged.Corrected_20kb.h5 \
--minDepth 60000 --maxDepth 120000 --numberOfProcessors 8 --step 20000 \
--outPrefix hic/marks_et-al_TADs_20kb-Bins  --minBoundaryDistance 80000 \
--correctForMultipleTesting fdr --threshold 0.05
```
What did I miss?

Thank you in advance.

Michal

**Comment by joachimwolff** [comment]
Hi Michal,

is the error message from one command? There are multiple tracebacks, usually you have only one per crash. Can you maybe clarify which error is raised by which command? 

The error of the last two `IOError: ``hic/replicateMerged.Corrected_20kb.h5`` does not exist` is raised because the specified matrix is not existing. Please check if the relative path you defined is really accessible. Try to use the absolute path if you are not sure. 

The error that the chromosomes are not found is sometimes caused by the mapper you used. There is an `ensembl` notation of chromosomes and a `UCSC` notation. The first one writes for e.g. chromsome 1 just `1`, but UCSC `chr1`. Try to plot the matrix without the `--chromosomes` parameter, what names are used in the plot? 

And last, if you like you can send me one of your matrices and I will have a closer look. 

Best,

Joachim

**Comment by joachimwolff** [comment]
Closed. Issue answered via mail, error caused by a wrong mapping, has nothing to do with HiCExplorer.
