### ISSUE TITLE
Error when trying to use hicBuildMatrix 

### ISSUE THREAD

**Issue by QianzhaoJ** [deeptools/HiCExplorer#284]
Hi
I tried to use hicBuildMatrix to create of a Hi-C matrix , but something is wrong . May be I should update pysam ？Please give me some suggestions , The version I used  is hicexplorer 2.2-dev .

> Traceback (most recent call last):
  File "/data1/liuzunpeng/04_Softwares/anaconda/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/data1/liuzunpeng/04_Softwares/anaconda/lib/python2.7/site-packages/hicexplorer/hicBuildMatrix.py", line 1209, in main
    pMinMappingQuality=args.minMappingQuality
  File "/data1/liuzunpeng/04_Softwares/anaconda/lib/python2.7/site-packages/hicexplorer/hicBuildMatrix.py", line 693, in readBamFiles
    mate2 = get_correct_map(mate2, mate2_supplementary_list)
  File "/data1/liuzunpeng/04_Softwares/anaconda/lib/python2.7/site-packages/hicexplorer/hicBuildMatrix.py", line 590, in get_correct_map 
    if op == pysam.CMATCH:
AttributeError: 'module' object has no attribute 'CMATCH'

Best

**Comment by joachimwolff** [comment]
Hi,

I am not quite sure if your bam files are broken or if there is some software issue. 

However, I see that you use the current development version with python 2.7. I recommend to use our stable master version, the development version can break and is currently developed with Python 3.6 and not tested with Python 2.7.

Best,

Joachim

**Comment by QianzhaoJ** [comment]
Thanks! I used development version because I need the  function `hicConvertFileFormats` . I need covert hicpro to h5 ,and I have solved this problem for updating `pysam` .
