### ISSUE TITLE
hicAdjustMatrix crashing when using regions bigger than Hi-C matrix bins coordinates

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#322]
When using a bed file with coordinates bigger than the Hi-C Matrix bins, `getRegionBinRange` function is crashing:

With `test.bed`:
```
2L    1000000    990000000
```

```hicAdjustMatrix -m HiC_matrices_corrected/control_2.5kb_cor.h5 --action keep -r Regions/test.bed -o HiC_matrices_corrected/control_2.5kb_test.h5```

```DEBUG:hicmatrix.HiCMatrix:Load self.matrixFileHandler
DEBUG:hicmatrix.lib.h5:Load in h5 format
ERROR:hicmatrix.HiCMatrix:Index error
Traceback (most recent call last):
  File "/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/site-packages/hicmatrix/HiCMatrix.py", line 250, in getRegionBinRange
    endbin = sorted(self.interval_trees[chrname][endpos:endpos + 1])[0].data
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/akhtar/group/richard/Softwares/anaconda2/bin/hicAdjustMatrix", line 7, in <module>
    main()
  File "/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/site-packages/hicexplorer/hicAdjustMatrix.py", line 90, in main
    start, end = hic_ma.getRegionBinRange(region[0], region[1], region[2])
TypeError: 'NoneType' object is not iterable```

**Comment by gtrichard** [comment]
I tried https://github.com/deeptools/HiCExplorer/pull/329 to fix it.
