### ISSUE TITLE
bulidMatrix error

### ISSUE THREAD

**Issue by hzaumsq** [deeptools/HiCExplorer#324]
when I use a big sam/bam(20G~30G) file after  bowtie2 or bwa , It seemed meet a mistake. The error information as follow !
The command I used ##：hicBuildMatrix --samFiles WHF4-1Hi-C_R1.sam WHF4-1Hi-C_R2.sam --binSize 40000 --restrictionSequence GATC --outFileName 40k.h5 --outBam WHF4-1Hi-C_40k.bam --QCfolder ./QC --threads 20 --inputBufferSize 400000 ###

Traceback (most recent call last):
  File "/public/home/dxbo/miniconda3/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/public/home/dxbo/miniconda3/lib/python3.6/site-packages/hicexplorer/hicBuildMatrix.py", line 1247, in main
    process[i].start()
  File "/public/home/dxbo/miniconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/public/home/dxbo/miniconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/public/home/dxbo/miniconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/public/home/dxbo/miniconda3/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/public/home/dxbo/miniconda3/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by joachimwolff** [comment]
Hi,

You run out of memory. What you can try is to reduce the number of cores, in my experience it is not giving a benefit to use more than 6 cores. Otherwise you need to split the bam files and build two or three smaller matrices and merge them afterwards. However the simplest solution is to run the jobs on a machine with more memory. If you don’t have access to more resources I can recommend hicexplorer.usegalaxy.eu. 

Best,

Joachim

**Comment by hzaumsq** [comment]
OK，I‘have solved this problem by taking your advise.That's very kind of you.
