### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by francicco** [deeptools/HiCExplorer#409]
Hi,

I'm struggling to install HiCAssembler because of compatibility of dependencies. I narrow down the issue and apparently HiCAssembler and HiCExplorer don't get along well because of these packadges

```
ERROR: hic2cool 0.7.3 has requirement cooler>=0.8.5, but you'll have cooler 0.8.2 which is incompatible.
ERROR: hicmatrix 10 has requirement cooler==0.8.5, but you'll have cooler 0.8.2 which is incompatible.
ERROR: hicmatrix 10 has requirement intervaltree==3.0.*, but you'll have intervaltree 2.1.0 which is incompatible.
ERROR: No matching distribution found for matplotlib==3.0.* (from HiCExplorer==3.0.2)
```

If I use python3 to install HiCExplorer is fine but HiCAssembler needs python2 otherwise I get this type of errors:

```
Traceback (most recent call last):
  File "/home/fc464/software/hicexplorer/bin/assemble", line 11, in <module>
    import hicassembler.HiCAssembler as HiCAssembler
  File "/home/fc464/software/hicexplorer/lib/python3.6/site-packages/hicassembler/HiCAssembler.py", line 226
    print self.N50
             ^
SyntaxError: Missing parentheses in call to 'print'
```

Any help?

Thanks a lot!
F

**Comment by joachimwolff** [comment]
HiCExplorer does no longer support Python 3. This dependency issue needs to be solved by HiCAssembler.

**Comment by francicco** [comment]
You mean no longer support Python 2. I guess!

**Comment by joachimwolff** [comment]
Ups, yes Python 2 :)

**Comment by francicco** [comment]
HiCAssembler require hicexplorer >= 2.1.1 but if I try do install that version this happen

```
Building wheels for collected packages: hicexplorer
  Building wheel for hicexplorer (setup.py) ... error
  ERROR: Complete output from command /home/fc464/software/HiCAssembler/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-J8lT92/hicexplorer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-POtJY5 --python-tag cp27:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/hicexplorer
  copying hicexplorer/readBed.py -> build/lib/hicexplorer
  copying hicexplorer/hicTransform.py -> build/lib/hicexplorer
  copying hicexplorer/hicFindTADspectra.py -> build/lib/hicexplorer
  copying hicexplorer/hicFindEnrichedContacts_old_version.py -> build/lib/hicexplorer
  copying hicexplorer/hicPlotTADs.py -> build/lib/hicexplorer
  copying hicexplorer/hicMergeMatrixBins.py -> build/lib/hicexplorer
  copying hicexplorer/_version.py -> build/lib/hicexplorer
  copying hicexplorer/liberman_load.py -> build/lib/hicexplorer
  copying hicexplorer/utilities.py -> build/lib/hicexplorer
  copying hicexplorer/__init__.py -> build/lib/hicexplorer
  copying hicexplorer/mapReduce.py -> build/lib/hicexplorer
  copying hicexplorer/hicFindTADs.py -> build/lib/hicexplorer
  copying hicexplorer/hicCorrelate.py -> build/lib/hicexplorer
  copying hicexplorer/hicPCA.py -> build/lib/hicexplorer
  copying hicexplorer/trackPlot.py -> build/lib/hicexplorer
  copying hicexplorer/iterativeCorrection.py -> build/lib/hicexplorer
  copying hicexplorer/hicInfo.py -> build/lib/hicexplorer
  copying hicexplorer/hicPrepareQCreport.py -> build/lib/hicexplorer
  copying hicexplorer/hicPlotDistVsCounts.py -> build/lib/hicexplorer
  copying hicexplorer/hicAggregateContacts.py -> build/lib/hicexplorer
  copying hicexplorer/hicBuildMatrix.py -> build/lib/hicexplorer
  copying hicexplorer/hicPlotMatrix.py -> build/lib/hicexplorer
  copying hicexplorer/hicCompareMatrices.py -> build/lib/hicexplorer
  copying hicexplorer/reduceMatrix.py -> build/lib/hicexplorer
  copying hicexplorer/hicCorrectMatrix.py -> build/lib/hicexplorer
  copying hicexplorer/hicLog2Ratio.py -> build/lib/hicexplorer
  copying hicexplorer/parserCommon.py -> build/lib/hicexplorer
  copying hicexplorer/list_tools.py -> build/lib/hicexplorer
  copying hicexplorer/hicLoopCalling.py -> build/lib/hicexplorer
  copying hicexplorer/hicPlotViewpoint.py -> build/lib/hicexplorer
  copying hicexplorer/hicFindEnrichedContacts.py -> build/lib/hicexplorer
  copying hicexplorer/HiCMatrix.py -> build/lib/hicexplorer
  copying hicexplorer/hicMergeTADbins.py -> build/lib/hicexplorer
  copying hicexplorer/findRestSite.py -> build/lib/hicexplorer
  copying hicexplorer/hicExport.py -> build/lib/hicexplorer
  copying hicexplorer/hicSumMatrices.py -> build/lib/hicexplorer
  running egg_info
  writing requirements to HiCExplorer.egg-info/requires.txt
  writing HiCExplorer.egg-info/PKG-INFO
  writing top-level names to HiCExplorer.egg-info/top_level.txt
  writing dependency_links to HiCExplorer.egg-info/dependency_links.txt
  warning: Failed to find the configured license file 'LICENSE'
  reading manifest file 'HiCExplorer.egg-info/SOURCES.txt'
  writing manifest file 'HiCExplorer.egg-info/SOURCES.txt'
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_scripts
  creating build/scripts-2.7
  copying and adjusting bin/findRestSite -> build/scripts-2.7
  copying and adjusting bin/hicAggregateContacts -> build/scripts-2.7
  copying and adjusting bin/hicBuildMatrix -> build/scripts-2.7
  copying and adjusting bin/hicCorrectMatrix -> build/scripts-2.7
  copying and adjusting bin/hicCorrelate -> build/scripts-2.7
  copying and adjusting bin/hicFindEnrichedContacts -> build/scripts-2.7
  copying and adjusting bin/hicFindTADs -> build/scripts-2.7
  copying and adjusting bin/hicMergeMatrixBins -> build/scripts-2.7
  copying and adjusting bin/hicPlotMatrix -> build/scripts-2.7
  copying and adjusting bin/hicPlotDistVsCounts -> build/scripts-2.7
  copying and adjusting bin/hicPlotTADs -> build/scripts-2.7
  copying and adjusting bin/hicSumMatrices -> build/scripts-2.7
  copying and adjusting bin/hicExport -> build/scripts-2.7
  copying and adjusting bin/hicInfo -> build/scripts-2.7
  copying and adjusting bin/hicexplorer -> build/scripts-2.7
  copying and adjusting bin/hicQC -> build/scripts-2.7
  copying and adjusting bin/hicCompareMatrices -> build/scripts-2.7
  copying and adjusting bin/hicPCA -> build/scripts-2.7
  copying and adjusting bin/hicTransform -> build/scripts-2.7
  copying and adjusting bin/hicPlotViewpoint -> build/scripts-2.7
  copying and adjusting bin/hicLog2Ratio -> build/scripts-2.7
  changing mode of build/scripts-2.7/findRestSite from 664 to 775
  changing mode of build/scripts-2.7/hicAggregateContacts from 664 to 775
  changing mode of build/scripts-2.7/hicBuildMatrix from 664 to 775
  changing mode of build/scripts-2.7/hicCorrectMatrix from 664 to 775
  changing mode of build/scripts-2.7/hicCorrelate from 664 to 775
  changing mode of build/scripts-2.7/hicFindEnrichedContacts from 664 to 775
  changing mode of build/scripts-2.7/hicFindTADs from 664 to 775
  changing mode of build/scripts-2.7/hicMergeMatrixBins from 664 to 775
  changing mode of build/scripts-2.7/hicPlotMatrix from 664 to 775
  changing mode of build/scripts-2.7/hicPlotDistVsCounts from 664 to 775
  changing mode of build/scripts-2.7/hicPlotTADs from 664 to 775
  changing mode of build/scripts-2.7/hicSumMatrices from 664 to 775
  changing mode of build/scripts-2.7/hicExport from 664 to 775
  changing mode of build/scripts-2.7/hicInfo from 664 to 775
  changing mode of build/scripts-2.7/hicexplorer from 664 to 775
  changing mode of build/scripts-2.7/hicQC from 664 to 775
  changing mode of build/scripts-2.7/hicCompareMatrices from 664 to 775
  changing mode of build/scripts-2.7/hicPCA from 664 to 775
  changing mode of build/scripts-2.7/hicTransform from 664 to 775
  changing mode of build/scripts-2.7/hicPlotViewpoint from 664 to 775
  changing mode of build/scripts-2.7/hicLog2Ratio from 664 to 775
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicSumMatrices.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicExport.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/findRestSite.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicMergeTADbins.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/HiCMatrix.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicFindEnrichedContacts.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicPlotViewpoint.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicLoopCalling.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/list_tools.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/parserCommon.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicLog2Ratio.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicCorrectMatrix.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/reduceMatrix.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicCompareMatrices.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicPlotMatrix.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicBuildMatrix.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicAggregateContacts.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicPlotDistVsCounts.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicPrepareQCreport.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicInfo.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/iterativeCorrection.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/trackPlot.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicPCA.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicCorrelate.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicFindTADs.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/mapReduce.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/__init__.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/utilities.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/liberman_load.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/_version.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicMergeMatrixBins.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicPlotTADs.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicFindEnrichedContacts_old_version.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicFindTADspectra.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/hicTransform.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  copying build/lib/hicexplorer/readBed.py -> build/bdist.linux-x86_64/wheel/hicexplorer
  warning: install_lib: byte-compiling is disabled, skipping.
  
  running install_egg_info
  Copying HiCExplorer.egg-info to build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1-py2.7.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data
  creating build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicLog2Ratio -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicPlotViewpoint -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicTransform -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicPCA -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicCompareMatrices -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicQC -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicexplorer -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicInfo -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicExport -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicSumMatrices -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicPlotTADs -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicPlotDistVsCounts -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicPlotMatrix -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicMergeMatrixBins -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicFindTADs -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicFindEnrichedContacts -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicCorrelate -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicCorrectMatrix -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicBuildMatrix -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/hicAggregateContacts -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  copying build/scripts-2.7/findRestSite -> build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicLog2Ratio to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicPlotViewpoint to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicTransform to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicPCA to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicCompareMatrices to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicQC to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicexplorer to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicInfo to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicExport to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicSumMatrices to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicPlotTADs to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicPlotDistVsCounts to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicPlotMatrix to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicMergeMatrixBins to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicFindTADs to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicFindEnrichedContacts to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicCorrelate to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicCorrectMatrix to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicBuildMatrix to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/hicAggregateContacts to 775
  changing mode of build/bdist.linux-x86_64/wheel/HiCExplorer-2.1.1.data/scripts/findRestSite to 775
  error: [Errno 2] No such file or directory: 'LICENSE'
  ----------------------------------------
  ERROR: Failed building wheel for hicexplorer
  Running setup.py clean for hicexplorer
Failed to build hicexplorer
ERROR: pygenometracks 2.1 has requirement pysam>=0.14, but you'll have pysam 0.11.2.2 which is incompatible.
ERROR: hic2cool 0.7.3 has requirement cooler>=0.8.5, but you'll have cooler 0.7.11 which is incompatible.
ERROR: hicmatrix 10 has requirement cooler==0.8.5, but you'll have cooler 0.7.11 which is incompatible.
ERROR: hicmatrix 10 has requirement future>=0.17.*, but you'll have future 0.16.0 which is incompatible.
ERROR: hicmatrix 10 has requirement intervaltree==3.0.*, but you'll have intervaltree 2.1.0 which is incompatible.
ERROR: hicmatrix 10 has requirement numpy>=1.16.*, but you'll have numpy 1.13.3 which is incompatible.
ERROR: hicmatrix 10 has requirement pandas>=0.24.*, but you'll have pandas 0.20.3 which is incompatible.
ERROR: hicmatrix 10 has requirement scipy>=1.2.*, but you'll have scipy 1.0.1 which is incompatible.
ERROR: hicmatrix 10 has requirement tables>=3.5.*, but you'll have tables 3.3.0 which is incompatible.
Installing collected packages: numpy, scipy, six, matplotlib, pysam, tables, pandas, future, cooler, jinja2, unidecode, hicexplorer
  Found existing installation: numpy 1.16.3
    Uninstalling numpy-1.16.3:
      Successfully uninstalled numpy-1.16.3
  Found existing installation: scipy 1.2.1
    Uninstalling scipy-1.2.1:
      Successfully uninstalled scipy-1.2.1
```

It's a bit of a mess...
F

**Comment by francicco** [comment]
It looks like it complains but then HiCAssembler does not.

```
(HiCAssembler) [fc464@login-e-16 bin]$ ./assemble --help
usage: assemble [-h] --matrix MATRIX --outFolder OUTFOLDER --fasta FASTA
                [--min_scaffold_length MIN_SCAFFOLD_LENGTH]
                [--bin_size BIN_SIZE] [--num_processors NUM_PROCESSORS]
                [--misassembly_zscore_threshold MISASSEMBLY_ZSCORE_THRESHOLD]
                [--num_iterations NUM_ITERATIONS]
                [--split_positions_file SPLIT_POSITIONS_FILE]
                [--scaffolds_to_ignore SCAFFOLDS_TO_IGNORE [SCAFFOLDS_TO_IGNORE ...]]

The idea is to test whether the contigs align next to each other. The format
of the matrix row labels should include the position of the contig.

optional arguments:
  -h, --help            show this help message and exit
  --matrix MATRIX, -m MATRIX
                        path of the Hi-C matrix. (default: None)
  --outFolder OUTFOLDER, -o OUTFOLDER
                        folder were to save output files. (default: None)
  --fasta FASTA, -f FASTA
                        fasta used for the hic (default: None)
  --min_scaffold_length MIN_SCAFFOLD_LENGTH
                        Minimum scaffold length for backbone to use. Using
                        larger (>300kb) scaffolds avoids the formation of
                        incorrect super-scaffolds. At a later stage the
                        smallerscaffolds are put back into the backbone. If
                        just few large scaffolds are available this parameter
                        should be decreased. (default: 300000)
  --bin_size BIN_SIZE   bin size (in bp) to use. Usually a high resolution
                        matrix is provided to the assembler. A lower
                        resolution matrix can be used if the depth of
                        sequencing is low. (default: 25000)
  --num_processors NUM_PROCESSORS
                        Number of processors to use. Multithreading is only
                        used to identify mis-assemblies. (default: 1)
  --misassembly_zscore_threshold MISASSEMBLY_ZSCORE_THRESHOLD, -mzt MISASSEMBLY_ZSCORE_THRESHOLD
                        To detect misasemblies, a z-score is computed similar
                        to the method used to identify TAD boundaries (see
                        HiCExploer `hicFindTADs`). Missassemblies appear as
                        strong TAD boundaries but it not straightforward to
                        distinguish true misassemblies from TAD boundaries. A
                        relax threshold is used by default because a false
                        positive (a TAD boundary that is thought to be a
                        misassembly) has a little impact on the assembly
                        compared to a false negative (a misassembly that was
                        not detected). However, the default parameter may
                        fragment the contigs/scaffolds to frequently and a
                        more stringent value is preferable. A simple way to
                        test if misasemblies are present is by inspecting the
                        resulting matrix by clear gaps. If this is the case,
                        change the zscore threshold to a larger value.
                        (default: -1)
  --num_iterations NUM_ITERATIONS
                        HiCAssembles aims to produce longer and longer hi-c
                        scaffolds in each iteration. The firsts iterations use
                        stringent criteria to join contigs/scaffolds. The
                        number of iterations required depend from sample to
                        sample. By observing the after_assembly_.pdf images
                        the desired number of iterations can be selected.
                        Usually no more than 3 iterations are required.
                        (default: 2)
  --split_positions_file SPLIT_POSITIONS_FILE
                        BED file. If the location of some mis-assemblies are
                        known, they can be provided on a bed file to be
                        splitted. The Hi-C matrix bin that overlaps with a
                        region in the bed file becomes the last bin before the
                        split. (default: None)
  --scaffolds_to_ignore SCAFFOLDS_TO_IGNORE [SCAFFOLDS_TO_IGNORE ...]
                        The assembly process is affected by scaffolds that
                        appear close to several other scaffolds. Normally, for
                        each scaffold a pair of neighbors can be identified,
                        however for some scaffolds several neighbors are
                        found. These problematic scaffolds could be caused by
                        misassemblies, duplications or repetitive regions.
                        Usually, better assemblies are produced by removing
                        this scaffolds initially. Then, when most of the
                        scaffolds are as assembled, the algorithm will try to
                        place those scaffolds back into the assembly. The
                        scaffolds should be separated by space: e.g.
                        scaffold_10 scafold_32 scaffold_27 (default: None)
```

**Comment by joachimwolff** [comment]
Just install all the tools with the version number (and not a newer one!) as mentioned in https://github.com/maxplanck-ie/HiCAssembler/blob/master/requirements.txt

This was the last tested status and should work.
