### ISSUE TITLE
cool to h5 convert

### ISSUE THREAD

**Issue by jiadong324** [deeptools/HiCExplorer#429]
I am using the command (below) to convert cool format to h5, so that I can use hicMatrixPlot.

`hicConvertFormat -m K562.50kb.cool -o K562.50kb --inputFormat cool --outputFormat h5`

But it raises errors, which shows:

`INFO:numexpr.utils:NumExpr defaulting to 4 threads.
Traceback (most recent call last):
  File "/usr/local/bin/hicConvertFormat", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/hicexplorer/hicConvertFormat.py", line 162, in main
    pApplyCorrectionCoolerLoad=applyCorrectionCoolerLoad)
  File "/usr/local/lib/python2.7/site-packages/hicmatrix/lib/matrixFileHandler.py", line 20, in __init__
    self.matrixFile = self.class_(pMatrixFile)
  File "/usr/local/lib/python2.7/site-packages/hicmatrix/lib/cool.py", line 26, in __init__
    super().__init__(pMatrixFile)
TypeError: super() takes at least 1 argument (0 given)`

Please help and thanks!

**Comment by joachimwolff** [comment]
Hi,

You do not need to convert cool to h5, HiCExplorer supports cool natively.

However, you get this error because you run HiCExplorer with Python 2.7 which is not supported by us. Please upgrade to Python 3.6.

Best,

Joachim

**Comment by jiadong324** [comment]
Thanks, I will upgrade my python version and use cool format directly.
