### ISSUE TITLE
Questions about hicMergeTADbins

### ISSUE THREAD

**Issue by QianzhaoJ** [deeptools/HiCExplorer#461]
Hi: 
The scripts :`hicMergeTADbins -m test.h5 --domains test.dm --outFile ./result.txt`
The errors:

> ERROR:hicmatrix.HiCMatrix:Index error
Traceback (most recent call last):
  File "/data1/liuzunpeng/04_Softwares/anaconda/envs/hicexplorer33/lib/python3.6/site-packages/hicmatrix/HiCMatrix.py", line 262, in getRegionBinRange
    endbin = sorted(self.interval_trees[chrname][endpos:endpos + 1])[0].data
IndexError: list index out of range
Traceback (most recent call last):
  File "/data2/liuzunpeng/04_Softwares/HiCExplorer-3.3.1/bin/hicMergeTADbins", line 7, in <module>
    main()
  File "/data1/liuzunpeng/04_Softwares/anaconda/envs/hicexplorer33/lib/python3.6/site-packages/hicexplorer/hicMergeTADbins.py", line 143, in main
    boundary_id_list = get_boundary_bin_id(hic_ma, args.domains)
  File "/data1/liuzunpeng/04_Softwares/anaconda/envs/hicexplorer33/lib/python3.6/site-packages/hicexplorer/hicMergeTADbins.py", line 129, in get_boundary_bin_id
    start_bin, end_bin = hic.getRegionBinRange(chrom, start, end)
TypeError: 'NoneType' object is not iterable

and the format  of `test.dm` :
   
> chr1	0	725000	ID1	.	.	0	725000	.
chr1	725000	1900000	ID2	.	.	725000	1900000	.
chr1	1900000	2000000	ID3	.	.	1900000	2000000	.
chr1	2000000	2600000	ID4	.	.	2000000	2600000	.

Could you give me some suggestions about the format of domians ?
Thanks in advance !

Qianzhao

**Comment by QianzhaoJ** [comment]
Hi :
Now I have worked out the problem about the format of input files , `hicMergeTADbins`  is running and no errors are reported . But I don't find the output files in `./result.txt` .
Qianzhao

**Comment by LeilyR** [comment]
`hic.getRegionBinRange(chrom, start, end)
TypeError: 'NoneType' object is not iterable` could mean that the coordinates went out of range

**Comment by LeilyR** [comment]
@QianzhaoJ We assume that your problem is solved since we have not heard of you. I close this issue for now but feel free to reopen it if there is still any problem left.
