### ISSUE TITLE
hicDetectLoops name not defined error

### ISSUE THREAD

**Issue by kelly-clark** [deeptools/HiCExplorer#492]
Hi,

I am trying to call loops in my Hi-C data using hicDetectLoops, and I am getting this error:

`Process Process-1:
Traceback (most recent call last):
  File "/users/sevans2/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/users/sevans2/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/users/sevans2/miniconda3/lib/python3.7/site-packages/hicexplorer/hicDetectLoops.py", line 595, in compute_loops
    pArgs.maxAllowedInteractionsSmallerOne)
  File "/users/sevans2/miniconda3/lib/python3.7/site-packages/hicexplorer/hicDetectLoops.py", line 215, in compute_long_range_contacts
    pMeanDifferenceNeighborhoodPeak, pMaxAllowedInteractionsSmallerOne)
  File "/users/sevans2/miniconda3/lib/python3.7/site-packages/hicexplorer/hicDetectLoops.py", line 349, in candidate_region_test
    neighborhood[i, :] = smoothInteractionValues(neihgborhood_unsmoothed[i, :], 5)
NameError: name 'neihgborhood_unsmoothed' is not defined`

When I changed "neihgborhood_unsmoothed" to "neighborhood_unsmoothed" I still had the same issue. How can I fix this?

Thanks,
Kelly

**Comment by joachimwolff** [comment]
Hi,

that one is unexpected. Before I start to have a closer look please consider two things: First, we do not support Python 3.7, only Python 3.6 is tested. And second, we released yesterday a new HiCExplorer version 3.4. Please test if it works with this latest version.
Best,
Joachim
----------------------------------------
Joachim Wolff
M.Sc. Computer Science
Bioinformatics Lab
Department of Computer Science
Albert-Ludwigs-University Freiburg
Georges-Koehler-Allee 079
D-79110 Freiburg

http://www.bioinf.uni-freiburg.de

**Comment by kelly-clark** [comment]
That seems to have solved the problem.
Thanks,
Kelly
