### ISSUE TITLE
hicDetectLoops attribute error

### ISSUE THREAD

**Issue by rachadele** [deeptools/HiCExplorer#503]
When I try to run hicDetectLoops on a cooler I get the following error, which repeats until I cancel the command:

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hicexplorer/hicDetectLoops.py", line 653, in compute_loops
    max_loop_distance)
  File "/usr/local/lib/python3.6/dist-packages/hicexplorer/hicDetectLoops.py", line 164, in compute_long_range_contacts
    nbinom_parameters = fit_nbinom.fit(
AttributeError: module 'fit_nbinom' has no attribute 'fit'

looks like there's something missing in the code for the binomial fitting module. any idea how to fix this?

**Comment by joachimwolff** [comment]
Hi,

that sounds really strange. How have you installed HiCExplorer and which version do you use? This sound for me a dependency is missing, please explain in detail what you have done and if you use conda environments.

Best,

Joachim
