### ISSUE TITLE
Cannot covert hic-pro matrix to h5 format

### ISSUE THREAD

**Issue by KunFang93** [deeptools/HiCExplorer#504]
Hi,

I would like to use hicConvertFormat command convert hic_pro matrix to h5 format but have the following error:

Traceback (most recent call last):
  File "/data/kun/miniconda3/envs/hicexplorer/bin/hicConvertFormat", line 7, in <module>
    main()
  File "/data/kun/miniconda3/envs/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicConvertFormat.py", line 167, in main
    distance_counts, correction_factors = matrixFileHandlerInput.load()
  File "/data/kun/miniconda3/envs/hicexplorer/lib/python3.6/site-packages/hicmatrix/lib/matrixFileHandler.py", line 45, in load
    return self.matrixFile.load()
  File "/data/kun/miniconda3/envs/hicexplorer/lib/python3.6/site-packages/hicmatrix/lib/hicpro.py", line 33, in load
    matrix = csr_matrix((data, (instances, features)), shape=(shape, shape))
  File "/data/kun/miniconda3/envs/hicexplorer/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 57, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File "/data/kun/miniconda3/envs/hicexplorer/lib/python3.6/site-packages/scipy/sparse/coo.py", line 198, in __init__
    self._check()
  File "/data/kun/miniconda3/envs/hicexplorer/lib/python3.6/site-packages/scipy/sparse/coo.py", line 289, in _check
    raise ValueError('negative row index found')
ValueError: negative row index found

The command I used is: hicConvertFormat -m ND18378_02_S5.iced.matrix --bedFileHicpro ../40000_abs.formal.bed --inputFormat hicpro --outputFormat h5 -o ND18378_02_S5.iced.h5

Thanks a lot!
Best,
Kun

**Comment by joachimwolff** [comment]
Can you show me how your matrix looks? The error is quite clear: 

`ValueError: negative row index found` 

A negative index value is not permitted, either your input has these kind of values really as an index. In this case we can't do anything for you. Or the input is having a different format than expected.

Best,

Joachim

**Comment by KunFang93** [comment]
my matrix looks like this 

0       0       2074.624724
0       4703    11.571463
0       6644    12.967634
0       12313   25.586158
0       20939   12.584735
0       26576   15.602163
0       27611   19.315453
0       29350   15.388112
0       33169   11.452808
0       43341   11.602878
0       45621   14.727914

I used awk '{if($1<0 || $2 <0||$3<0){print $0}}' ND18378_02_S5.iced.matrix_ to check whether there is negative index but nothing found. Thanks  a lot!

**Comment by KunFang93** [comment]
I might found the problem, the bin index should start from 1 instead of 0. Thanks~

**Comment by MzwaneleN** [comment]
Hi @KunFang93 can I please ask you something about conversion of hic_pro matrix to h5 format, privately? I just received hic_pro data and I want to analyze it in hicexplorer and I would like a few pointers to get me going. Thanks

**Comment by KunFang93** [comment]
> Hi @KunFang93 can I please ask you something about conversion of hic_pro matrix to h5 format, privately? I just received hic_pro data and I want to analyze it in hicexplorer and I would like a few pointers to get me going. Thanks

This link might help:https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html
