### ISSUE TITLE
hicPCA gene track format

### ISSUE THREAD

**Issue by pqyNUS** [deeptools/HiCExplorer#524]
Hi,

I tried to run the hicPCA using the gene bed file as follows:

#chrom | start | end | name | score | strand | thickStart | thickEnd | rgb
chr1 | 11868 | 14409 | DDX11L1 | 1000 | + | 11868 | 14409 | .

but i get the following error, which i suppose is the wrong format of the bed file:

ERROR:hicmatrix.HiCMatrix:Index error
Traceback (most recent call last):
  File "/hpctmp2/a0123882/hicexplorer/lib/python3.6/site-packages/hicmatrix/HiCMatrix.py", line 261, in getRegionBinRange
    startbin = sorted(self.interval_trees[chrname][startpos:startpos + 1])[0].data
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpctmp2/a0123882/hicexplorer/bin/hicPCA", line 7, in <module>
    main()
  File "/hpctmp2/a0123882/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicPCA.py", line 334, in main
    vecs_list = correlateEigenvectorWithGeneTrack(ma, vecs_list, args.extraTrack)
  File "/hpctmp2/a0123882/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicPCA.py", line 158, in correlateEigenvectorWithGeneTrack
    gene_occurrence[bin_id[1]] += 1
TypeError: 'NoneType' object is not subscriptable

May i know the format of the gene track required? as i tried many times with other formats. i could not get it to work

Thanks in advance.

Eddy

**Comment by LeilyR** [comment]
could you please try 4 columns file (chr,start,end,score) with no header?

**Comment by pqyNUS** [comment]
i tried 4 columns without the header and i got the following error:

TypeError: Expected 6 arguments, got 4
