### ISSUE TITLE
hicexplorer3.4.1 plotting modules cannot be used in python notebooks

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#536]
This is new to 3.4 , at least it was possible to do it up to 3.1. the issue comes from the matplotlib version I suspect. The error is:
`Traceback (most recent call last):
  File "/package/anaconda3/envs/HiCExplorer-3.4.3/bin/hicPlotMatrix", line 4, in <module>
    from hicexplorer.hicPlotMatrix import main
  File "/package/anaconda3/envs/HiCExplorer-3.4.3/lib/python3.6/site-packages/hicexplorer/hicPlotMatrix.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/package/anaconda3/envs/HiCExplorer-3.4.3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2356, in <module>
    switch_backend(rcParams["backend"])
  File "/package/anaconda3/envs/HiCExplorer-3.4.3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/package/anaconda3/envs/HiCExplorer-3.4.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'ipykernel'`

**Comment by LeilyR** [comment]
the temporary solution for that will be installing ipykernel to the same env.

**Comment by LeilyR** [comment]
#576 takes care of it.
