### ISSUE TITLE
hicFindTADs: Memory Error 

### ISSUE THREAD

**Issue by YichaoOU** [deeptools/HiCExplorer#588]
I used hicpro to generate interaction matrix, and then used `hicConvertFormat` to convert the matrix into `h5` format.

```
hicConvertFormat --matrices ./iced/1000/{{sample_id}}_1000_iced.matrix --outFileName {{sample_id}}.hicexplorer_1kb --inputFormat hicpro --outputFormat h5 --bedFileHicpro ./raw/1000/{{sample_id}}_1000_abs.bed 
```

This generated `h5` file is 4.6G.

Next, I used `hicFindTADs` to find TADs

```
hicFindTADs --matrix {{sample_id}}.hicexplorer_1kb.h5 --correctForMultipleTesting fdr --outPrefix {{sample_id}}.hicexplorer_1kb.tad -p 8 
```

I got the following Out of Memory Error:

```
INFO:hicexplorer.hicFindTADs:removing diagonal values

INFO:hicexplorer.hicFindTADs:Computing z-score matrix...

Traceback (most recent call last):
  File "/home/yli11/.conda/envs/hicexplorer/bin/hicFindTADs", line 7, in <module>
    main()
  File "/home/yli11/.conda/envs/hicexplorer/lib/python3.7/site-packages/hicexplorer/hicFindTADs.py", line 1376, in main
    ft.compute_spectra_matrix()
  File "/home/yli11/.conda/envs/hicexplorer/lib/python3.7/site-packages/hicexplorer/hicFindTADs.py", line 1068, in compute_spectra_matrix
    self.hic_ma.convert_to_zscore_matrix(maxdepth=self.max_depth * 2.5, perchr=perchr)
  File "/home/yli11/.conda/envs/hicexplorer/lib/python3.7/site-packages/hicmatrix/HiCMatrix.py", line 352, in convert_to_zscore_matrix
    return self.convert_to_obs_exp_matrix(maxdepth=maxdepth, zscore=True, perchr=perchr)
  File "/home/yli11/.conda/envs/hicexplorer/lib/python3.7/site-packages/hicmatrix/HiCMatrix.py", line 562, in convert_to_obs_exp_matrix
    trasf_matrix[chrom_range[chrname][0]:chrom_range[chrname][1], chrom_range[chrname][0]:chrom_range[chrname][1]] = submatrix.tolil()
  File "/home/yli11/.conda/envs/hicexplorer/lib/python3.7/site-packages/scipy/sparse/lil.py", line 333, in __setitem__
    IndexMixin.__setitem__(self, key, x)
  File "/home/yli11/.conda/envs/hicexplorer/lib/python3.7/site-packages/scipy/sparse/_index.py", line 116, in __setitem__
    self._set_arrayXarray_sparse(i, j, x)
  File "/home/yli11/.conda/envs/hicexplorer/lib/python3.7/site-packages/scipy/sparse/lil.py", line 319, in _set_arrayXarray_sparse
    x = np.asarray(x.toarray(), dtype=self.dtype)
  File "/home/yli11/.conda/envs/hicexplorer/lib/python3.7/site-packages/scipy/sparse/coo.py", line 321, in toarray
    B = self._process_toarray_args(order, out)
  File "/home/yli11/.conda/envs/hicexplorer/lib/python3.7/site-packages/scipy/sparse/base.py", line 1185, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
MemoryError: Unable to allocate 463. GiB for an array with shape (249256, 249256) and data type float64
```

I think it is better to use high-resolution interactions for TAD calling, right?  Any ideas how I can solve this memory problem? 463G is just too much. Maybe I can reduce the `-p` option to use fewer cores? Or maybe I should call TADs for each chr separately?

Thanks,
Yichao

**Comment by LeilyR** [comment]
Hey, 1kb resolution is indeed a bit too high for TAD detection, please consider lowering it (if working on big genomes like human, something just around 10k would still be fine). If you are having a lot of contigs, also not a bad idea to exclude them and keep your main chromosomes. We will working on optimizing the process of finding TADs in future but unfortunately at the moment is a bit memory consume.
