### ISSUE TITLE
PlotMatrix from .cool matrix

### ISSUE THREAD

**Issue by foertsch** [deeptools/HiCExplorer#605]
`SlurmEasy -m 10G -t 12 -l logs 'hicPlotMatrix --matrix matrix_corrected.cool  --outFileName matrix_corrected_cool_log1p.png --log1p '`

`INFO:hicexplorer.hicPlotMatrix:Cooler or no cooler: True
Traceback (most recent call last):
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/bin/hicPlotMatrix", line 7, in <module>
    main()
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/lib/python3.7/site-packages/hicexplorer/hicPlotMatrix.py", line 717, in main
    ma = HiCMatrix.hiCMatrix(args.matrix, pChrnameList=regionsToRetrieve)
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/lib/python3.7/site-packages/hicmatrix/HiCMatrix.py", line 55, in __init__
    matrixFileHandler_load = self.matrixFileHandler.load()
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/lib/python3.7/site-packages/hicmatrix/lib/matrixFileHandler.py", line 57, in load
    return self.matrixFile.load()
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/lib/python3.7/site-packages/hicmatrix/lib/cool.py", line 125, in load
    matrix = cooler_file.matrix(balance=False, sparse=True, as_pixels=False).fetch(self.chrnameList[0]).tocsr()
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/lib/python3.7/site-packages/cooler/core.py", line 574, in fetch
    return self._slice(self.field, i0, i1, j0, j1)
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/lib/python3.7/site-packages/cooler/api.py", line 376, in _slice
    self._is_symm_upper,
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/lib/python3.7/site-packages/cooler/api.py", line 715, in matrix
    i, j, v = query_rect(reader.query, i0, i1, j0, j1, duplex=True)
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/lib/python3.7/site-packages/cooler/core.py", line 372, in query_rect
    i, j, v = triu_reader(i0, i1, i0, i1)
  File "/package/anaconda3/envs/HiCExplorer-3.5.1/lib/python3.7/site-packages/cooler/core.py", line 262, in query
    p0, p1 = edges[0], edges[-1]
IndexError: index 0 is out of bounds for axis 0 with size 0
srun: error: deep9: task 0: Exited with exit code 1
srun: Terminating job step 449705.0
foertsch.20200923_090027.449705.err (END)`

**Comment by joachimwolff** [comment]
@nvictus This is an error coming from the cooler package. Any idea what goes wrong?

**Comment by foertsch** [comment]
I converted a .h5 matrix to a .cool matrix using hicConvertFormat. Subsequently used hicMergeMatrixBins and hicCorrectMatrix before trying to plot. The plot works for the .h5 format but not for the .cool

**Comment by nvictus** [comment]
Could you paste the output of `cooler tree matrix_corrected.cool`?

**Comment by joachimwolff** [comment]
@foertsch Can you give us some information a) about what Nezar asked for and b) can you determine if there is difference in the tools i.e. can you plot after hicConvertFormat but maybe not after you applied hicMergeMatrixBins, etc? Without your detailed feedback it is very difficult to figure out what is actually wrong.

**Comment by joachimwolff** [comment]
Unresponsive questioner. Closing this issue now.
