### ISSUE TITLE
h5 format in 3.5.3

### ISSUE THREAD

**Issue by PerrineLacour** [deeptools/HiCExplorer#619]
Hello, 

I used hicPCA (version 3.5.3) on Hi-C matrices 
` hicPCA --matrix matrix.h5 -o PC1.bw PC2.bw -pm Pearson.h5 `
and then wanted to look at the hicInfo results on the Pearson matrix
` hicInfo --matrices Pearson.h5 -o PearsonInfo.txt `
and got the following error
`Traceback (most recent call last):
  File "/g/funcgen/gbcs/public/software/conda/envs/hicexplorer-3.5.3/bin/hicInfo", line 7, in <module>
    main()
  File "/g/funcgen/gbcs/public/software/conda/envs/hicexplorer-3.5.3/lib/python3.6/site-packages/hicexplorer/hicInfo.py", line 123, in main
    hic_ma = hm.hiCMatrix(matrix)
  File "/g/funcgen/gbcs/public/software/conda/envs/hicexplorer-3.5.3/lib/python3.6/site-packages/hicmatrix/HiCMatrix.py", line 55, in __init__
    matrixFileHandler_load = self.matrixFileHandler.load()
  File "/g/funcgen/gbcs/public/software/conda/envs/hicexplorer-3.5.3/lib/python3.6/site-packages/hicmatrix/lib/matrixFileHandler.py", line 57, in load
    return self.matrixFile.load()
  File "/g/funcgen/gbcs/public/software/conda/envs/hicexplorer-3.5.3/lib/python3.6/site-packages/hicmatrix/lib/h5.py", line 35, in load
    matrix = csr_matrix(tuple([parts['data'], parts['indices'], parts['indptr']]),
KeyError: 'data'`
I tried with hicInfo-3.4.3, which is able to open the Pearson.h5 file.

Do you know where this bug comes from? Should I transform the matrix into another format?

Thanks for your help!

**Comment by PerrineLacour** [comment]
After some tests and reading the code, I realised that actually, I used 
`-pm Pearson` and not `-pm Pearson.h5` which lead to a Pearson matrix in a cool format (I think) renamed into Pearson.h5 afterwards.
My bad!
I close the issue, since it was only a mistake, but I think it could be useful to add this multiple formats thing into the documentation!
