### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by CocoMlle** [deeptools/HiCExplorer#751]
Hi, i was trying to install HiCExplorer by all the way but with no success: 

i tried conda: 
conda install hicexplorer -c bioconda -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

ResolvePackageNotFound: 
  - python=3.6.2

then pip :

pip3 install hicexplorer
Traceback (most recent call last):
  File "/work/gad/shared/bin/miniconda3/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 8, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/pip/_internal/cli/progress_bars.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/pip/_internal/utils/logging.py", line 14, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 29, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/pip/_internal/locations/_sysconfig.py", line 8, in <module>
    from pip._internal.exceptions import InvalidSchemeCombination, UserInstallationInvalid
ImportError: cannot import name 'InvalidSchemeCombination'

and i tried with the github repo, it's kind of working but with the same bug than already reported, i can't launch hicexplorer:

./hicexplorer 
Traceback (most recent call last):
  File "./hicexplorer", line 11, in <module>
    main(args)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/hicexplorer/list_tools.py", line 93, in main
    process_args(args)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/hicexplorer/list_tools.py", line 85, in process_args
    args = parse_arguments().parse_args(args)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/argparse.py", line 1024, in __call__
    parser.print_help()
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/argparse.py", line 2372, in _print_message
    file.write(message)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 985: ordinal not in range(256)

do you have any idea what can i do more ?

i'm working on server with rhel fedora 7 and python 3.6 is the current version installed.
thanks for your help !

**Comment by CocoMlle** [comment]
sorry i answered here if it can help you :
i found what is wrong for the UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 985: ordinal not in range(256)

in this file : miniconda3/lib/python3.6/site-packages/hicexplorer/list_tools.py
"Nucleic Acids Research, Volume 46, Issue W1, 2 July 2018, Pages W11-W16, doi: https://doi.org/10.1093/nar/gky504" => there were originally some "<" around W11 and W16 and some extra character, i removed all and just add some "-" and it's working fine!

**Comment by lldelisle** [comment]
Hi,
Alternatively you can install with conda with python 3.7. At least into a fresh environment it works:
```
conda create -n hicexplorer -c bioconda -c conda-forge hicexplorer=3.7.1 python=3.7
```

**Comment by adrisede** [comment]
Hi! 

I'm trying to install it without success as well. 

I tried:   

conda create -n hicexplorer -c bioconda -c conda-forge hicexplorer=3.7.1 python=3.7

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.   
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
hicexplorer=3.7.1 -> python[version='>=3.6']
hicexplorer=3.7.1 -> biopython[version='<1.77'] -> python[version='2.7.*|3.5.*|3.6.*|3.4.*|>=3.6,<3.7.0a0|>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|<3.7|>=3.9,<3.10.0a0|>=3|>=3.7.1,<3.8.0a0|<3.0.0|>=2.7|>=3.5|2.7|>=3.5']
python=3.7The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - feature:|@/linux-64::__glibc==2.28=0

Your installed version is: 2.28

Note that strict channel priority may have removed packages required for satisfiability.
