### ISSUE TITLE
 hicPlotMatrix   killed

### ISSUE THREAD

**Issue by Zheng19w** [deeptools/HiCExplorer#800]
**Welcome to the HiCExplorer GitHub repository! Before opening the issue please check
 that the following requirements are met :**

- [ ] Search whether this issue (or a similar issue) has been solved before using the search tab above. Link the previous issue if appropriate below.

- [ ] Paste your HiCExplorer version (`hicInfo --version`) and your python version (`python --version`) below. 
- [ ] Have you checked our documentation on [hicexplorer.readthedocs.io](https://hicexplorer.readthedocs.io)?
- [ ] Do you use [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) to install HiCExplorer? 
- [ ] Do you use the latest HiCExplorer release? If not, please install it via a conda environment: 
       `conda create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge`
       and activate the environment: `conda activate hicexplorer`.  Retry your command. You can exit a conda environment via `conda deactivate`. To learn more about conda and environments, please consider the following [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#).

Retry your command, is it solved now? If not please continue with the following:
- [ ] Paste the full HiCExplorer command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

- [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).
Dear Professor

When I use hicPlotMatrix, I keep reporting errors. How to solve this problem

 -rw-rw-r-- 1 zheng1996 zheng1996 9.1K Jun  4 00:23 hicpro2cool1.sh.log
-rw-rw-r-- 1 zheng1996 zheng1996  417 Jun  4 18:19 hicpro2cool.sh
-rw-rw-r-- 1 zheng1996 zheng1996 8.3K Jun  4 18:26 hicpro2cool.sh.log
-rw-rw-r-- 1 zheng1996 zheng1996  314 Jun  4 12:42 scrofa.fa.sizes
-rw-rw-r-- 1 zheng1996 zheng1996 179M Jun  4 18:26 scrofa-Hi-C-muscle.10000.cool
-rw-rw-r-- 1 zheng1996 zheng1996  251 Jun  4 00:54 Sus_scrofa.fa.sizes

/public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/hicexplore/bin/hicPlotMatrix --matrix /public/home/zheng1996/Hic/hicpro2cool/scrofa-Hi-C-muscle.10000.cool --outFileName hicexplore_plot.png --log --dpi 300

INFO:numexpr.utils:Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO:numexpr.utils:Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
Killed

**Comment by Zheng19w** [comment]
hicConvertFormat --matrices  /public/home/zheng1996/Hic/hicpro2cool/scrofa-Hi-C-muscle.10000.cool  --outFileName  scrofa-Hi-C-muscle.10000.h5 --inputFormat  cool     --outputFormat  h5

/public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/hicexplore/bin/hicPlotMatrix --matrix scrofa-Hi-C-muscle.10000.h5 --outFileName hicexplore_plot.png --log --dpi 300

INFO:numexpr.utils:Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO:numexpr.utils:Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:hicexplorer.hicPlotMatrix:min: 0.011780609837, max: 3954.39214713

Killed

**Comment by Zheng19w** [comment]
-rw-rw-r-- 1 zheng1996 zheng1996    0 Jun  4 18:52 hicexplore_plot.png
-rw-rw-r-- 1 zheng1996 zheng1996 9.1K Jun  4 00:23 hicpro2cool1.sh.log
-rw-rw-r-- 1 zheng1996 zheng1996  417 Jun  4 18:19 hicpro2cool.sh
-rw-rw-r-- 1 zheng1996 zheng1996 8.3K Jun  4 18:26 hicpro2cool.sh.log
-rw-rw-r-- 1 zheng1996 zheng1996  314 Jun  4 12:42 scrofa.fa.sizes
-rw-rw-r-- 1 zheng1996 zheng1996 179M Jun  4 18:26 scrofa-Hi-C-muscle.10000.cool
-rw-rw-r-- 1 zheng1996 zheng1996 954M Jun  4 18:52 scrofa-Hi-C-muscle.10000.h5
-rw-rw-r-- 1 zheng1996 zheng1996  251 Jun  4 00:54 Sus_scrofa.fa.sizes

**Comment by Zheng19w** [comment]
INFO:numexpr.utils:Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO:numexpr.utils:Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:hicexplorer.hicPlotMatrix:min: 0.011780609837, max: 3954.39214713

Traceback (most recent call last):
  File "/public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/hicexplore/bin/hicPlotMatrix", line 7, in <module>
    main()
  File "/public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/hicexplore/lib/python2.7/site-packages/hicexplorer/hicPlotMatrix.py", line 537, in main
    matrix = np.asarray(ma.getMatrix().astype(float))
  File "/public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/hicexplore/lib/python2.7/site-packages/hicmatrix/HiCMatrix.py", line 176, in getMatrix
    matrix = self.matrix.todense()
  File "/public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/hicexplore/lib/python2.7/site-packages/scipy/sparse/base.py", line 849, in todense
    return np.asmatrix(self.toarray(order=order, out=out))
  File "/public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/hicexplore/lib/python2.7/site-packages/scipy/sparse/compressed.py", line 962, in toarray
    out = self._process_toarray_args(order, out)
  File "/public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/hicexplore/lib/python2.7/site-packages/scipy/sparse/base.py", line 1187, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
MemoryError

**Comment by Dooozy** [comment]
you can try adding"--perChromosome".
