### ISSUE TITLE
`list index out of range` of `hicMergeDomains`

### ISSUE THREAD

**Issue by shenlinyong** [deeptools/HiCExplorer#803]
This software you have developed is fantastic! But I have a problem when I use the `hicMergeDomains` to merge TAD files in multiple resolutions, how should I solve it?
```bash
hicexplorer=3.7.2 python=3.8.8
```

```bash
hicMergeDomains --domainFiles ../fat_5000_Normalize_domains.bed ../fat_10000_Normalize_domains.bed ../fat_25000_Normalize_domains.bed ../fat_50000_Normalize_domains.bed
Saved relation tree of NC_052532.1
Saved relation tree of NC_052533.1
Saved relation tree of NC_052534.1
Traceback (most recent call last):
  File "/home/SLY68/anaconda3/bin/hicMergeDomains", line 7, in <module>
    main()
  File "/home/SLY68/anaconda3/lib/python3.8/site-packages/hicexplorer/hicMergeDomains.py", line 428, in main
    create_tree(relationList, mergedListWithId, args.outputTreePlotPrefix, args.outputTreePlotFormat)
  File "/home/SLY68/anaconda3/lib/python3.8/site-packages/hicexplorer/hicMergeDomains.py", line 280, in create_tree
    while int(sList[posSList][1][0][3:]) < int(rList[posRList][1][3:]):
IndexError: list index out of range
```

**Comment by usernicai** [comment]
@shenlinyong 
Hello, I have encountered the same problem. Have you found a solution？
