### ISSUE TITLE
can't use hicDetectLoops 

### ISSUE THREAD

**Issue by jrw510** [deeptools/HiCExplorer#810]
hello,
i used conda to install hicexplorer in a new environment, but i can't use hicDetectLoops or hicHyperoptDetectLoops,

$ hicDetectLoops -h
Traceback (most recent call last):
  File "/data/jerry/software/miniconda3/envs/hicexplorer/bin/hicDetectLoops", line 4, in <module>
    from hicexplorer.hicDetectLoops import main
  File "/data/jerry/software/miniconda3/envs/hicexplorer/lib/python3.9/site-packages/hicexplorer/hicDetectLoops.py", line 22, in <module>
    from hicexplorer.lib import cnb
  File "/data/jerry/software/miniconda3/envs/hicexplorer/lib/python3.9/site-packages/hicexplorer/lib/__init__.py", line 2, in <module>
    from .tadClassifier import TADClassifier
  File "/data/jerry/software/miniconda3/envs/hicexplorer/lib/python3.9/site-packages/hicexplorer/lib/tadClassifier.py", line 41, in <module>
    from cleanlab.classification import LearningWithNoisyLabels
ImportError: cannot import name 'LearningWithNoisyLabels' from 'cleanlab.classification' (/data/jerry/software/miniconda3/envs/hicexplorer/lib/python3.9/site-packages/cleanlab/classification.py)

$ hicHyperoptDetectLoops -h
Traceback (most recent call last):
  File "/data/jerry/software/miniconda3/envs/hicexplorer/bin/hicHyperoptDetectLoops", line 4, in <module>
    from hicexplorer.hicHyperoptDetectLoops import main
  File "/data/jerry/software/miniconda3/envs/hicexplorer/lib/python3.9/site-packages/hicexplorer/hicHyperoptDetectLoops.py", line 11, in <module>
    from hicexplorer import hicDetectLoops
  File "/data/jerry/software/miniconda3/envs/hicexplorer/lib/python3.9/site-packages/hicexplorer/hicDetectLoops.py", line 22, in <module>
    from hicexplorer.lib import cnb
  File "/data/jerry/software/miniconda3/envs/hicexplorer/lib/python3.9/site-packages/hicexplorer/lib/__init__.py", line 2, in <module>
    from .tadClassifier import TADClassifier
  File "/data/jerry/software/miniconda3/envs/hicexplorer/lib/python3.9/site-packages/hicexplorer/lib/tadClassifier.py", line 41, in <module>
    from cleanlab.classification import LearningWithNoisyLabels
ImportError: cannot import name 'LearningWithNoisyLabels' from 'cleanlab.classification' (/data/jerry/software/miniconda3/envs/hicexplorer/lib/python3.9/site-packages/cleanlab/classification.py)

thanks for your help!

**Comment by jrw510** [comment]
$ hicexplorer --version
hicexplorer 3.7.2
$ python --version
Python 3.9.13

**Comment by joachimwolff** [comment]
Seems that a dependency changed its API. Please try to install HiCExplorer with a fixed version number for this dependency:
`conda install hicexplorer cleanlab=0.1 -c bioconda -c conda-forge`

Best,

Joachim

**Comment by jrw510** [comment]
it works. thank you!

**Comment by sebastian-gregoricchio** [comment]
I had similar issue and I solved installing this exact version of cleanlab in my conda env:

`conda install -c conda-forge 'cleanlab=1.0.1=pyhd8ed1ab_0'`

**Comment by Norbittner** [comment]
The same is true when installing HiCExplorer by cloning the repository it's not working with the current version of cleanlab 2.0.0 but when switching to 1.0.1 it's working fine.

**Comment by tolender** [comment]
Had this same error message but used "conda install hicexplorer cleanlab=0.1 -c bioconda -c conda-forge" as suggested and it worked. Can you update the main page to make it clearer for others?

Thank you so much!
