### ISSUE TITLE
unboundLocalError: local variable 'out_bam_file' referenced before assignment

### ISSUE THREAD

**Issue by theshowmustgolangon** [deeptools/HiCExplorer#823]
**Welcome to the HiCExplorer GitHub repository! Before opening the issue please check
 that the following requirements are met :**

- [x] Search whether this issue (or a similar issue) has been solved before using the search tab above. Link the previous issue if appropriate below.

- [x] Paste your HiCExplorer version (`hicInfo --version`) and your python version (`python --version`) below. 
- [x] Have you checked our documentation on [hicexplorer.readthedocs.io](https://hicexplorer.readthedocs.io)?
- [x] Do you use [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) to install HiCExplorer? 
- [x] Do you use the latest HiCExplorer release? If not, please install it via a conda environment: 
       `conda create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge`
       and activate the environment: `conda activate hicexplorer`.  Retry your command. You can exit a conda environment via `conda deactivate`. To learn more about conda and environments, please consider the following [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#).

Retry your command, is it solved now? If not please continue with the following:
- [x] Paste the full HiCExplorer command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

- [x] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

hicInfo 3.7.2
Python 3.10.6
command: 
hicBuildMatrix --samFiles smpl_R1.bam smpl_R2.bam \
--binSize 1000 5000 10000 50000 25000 50000 100000 250000 500000 1000000 2500000 \
--restrictionSequence GAATC GAGTC GATTC GACTC GATC CTAAG CTGAG CTTAG CTCAG TTAA \
--danglingSequence AAT AGT ATT ACT GATC TAA TGA TTA TCA TA 
--restrictionCutFile GAATC.bed GAGTC.bed GATTC.bed GACTC.bed GATC.bed CTAAG.bed CTGAG.bed CTTAG.bed CTCAG.bed TTAA.bed \
--threads 4 --inputBufferSize 400000 --outBam smpl_hicexplorer_hic.bam \
--outFileName smpl_hicexplorer_hic_matrix.h5 \
--chromosomeSizes chrom.sizes \
--genomeAssembly rn7chr.fa \
--doTestRun --doTestRunLines 1000000 \
--QCfolder hicQC/

After running, I got an error, 
Traceback (most recent call last):
  File "hicexplorer/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "hicexplorer/lib/python3.10/site-packages/hicexplorer/hicBuildMatrix.py", line 1400, in main
    out_bam_file.write(mate1)
UnboundLocalError: local variable 'out_bam_file' referenced before assignment

And, it seems to be stuck. Could you help me to solve this error if it is stuck and errors please?

**Comment by theshowmustgolangon** [comment]
I ran it just /hicQuickQC command, and it doesn't cause any errors.
