### ISSUE TITLE
hicBuildMatrix error

### ISSUE THREAD

**Issue by linkous123** [deeptools/HiCExplorer#847]
I run the hicBuildMatrix(I use a subset) :
hicBuildMatrix --samFiles subset_R1.bam subset_R2.bam --binSize 20000 --restrictionSequence GATC --danglingSequence GATC --restrictionCutFile cut_sites.bed --outBam subset.bam --outFileName ./subset_20kb.h5 --QCfolder ./subset_20kb_QC --threads 8 --inputBufferSize 400000
it return :
INFO:hicexplorer.hicBuildMatrix:reading subset_R1.bam and subset_R2.bam to build hic_matrix

[E::idx_find_and_load] Could not retrieve index file for 'subset_R1.bam'
[E::idx_find_and_load] Could not retrieve index file for 'subset_R2.bam'
INFO:hicexplorer.hicBuildMatrix:dangling sequences to check are {'GATC': {'pat_forw': 'GATC', 'pat_rev': 'GATC'}}

INFO:hicexplorer.hicBuildMatrix:processing 10000 lines took 2.33 secs (4289.1 lines per second)

INFO:hicexplorer.hicBuildMatrix:5722 (57.22%) valid pairs added to matrix

Traceback (most recent call last):
  File "/data2/chenkai/limaor/miniconda3/envs/hice/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/data2/chenkai/limaor/miniconda3/envs/hice/lib/python3.9/site-packages/hicexplorer/hicBuildMatrix.py", line 1585, in main
    QC.main("-l {} -o {}".format(log_file_name, args.QCfolder).split())
  File "/data2/chenkai/limaor/miniconda3/envs/hice/lib/python3.9/site-packages/hicexplorer/hicPrepareQCreport.py", line 325, in main
    save_html(args.outputFolder + "/hicQC.html", unmap_table, discarded_table, distance_table,
  File "/data2/chenkai/limaor/miniconda3/envs/hice/lib/python3.9/site-packages/hicexplorer/hicPrepareQCreport.py", line 66, in save_html
    html_content = html_content.replace("%%TABLE_UNMAP%%", unmap_table.style
AttributeError: 'Styler' object has no attribute 'render'

the installation command:
mamba create -n hice python=3.9.15
conda activate hice
mamba install hicecplorer=3.7.2

the hicexplorer version:
hicexplorer               3.7.2              pyhdfd78af_1    bioconda

I follow the tutorial(javascript:;)(https://hicexplorer.readthedocs.io/en/latest/) to bwa mem :
bwa mem -A 1 -B 4 -E 50 -L 0 -t 8 /gtf_fasta/chicken_GRCg6a/Gallus_gallus.fa ./subset_R1.fastq.gz | samtools view -Shb - > SWF-1.clean_R1.bam

bwa mem -A 1 -B 4 -E 50 -L 0 -t 8 /gtf_fasta/chicken_GRCg6a/Gallus_gallus.fa ./subset.clean_R2.fastq.gz | samtools view -Shb - > SWF-1.clean_R2.bam

ps : the error looks like cased by pandas, but my pandas is the latest version:
pandas                    2.0.0            py39h2ad29b5_0    conda-forge

**Comment by sqwwww** [comment]
hi, I met the same problem, do you have any solution till now?

**Comment by Normanteo** [comment]
Hi, I also have the same issue. anyone has any idea on how to solve this?

**Comment by Ssmile333** [comment]
> Hi, I also have the same issue. anyone has any idea on how to solve this?

Try installing python 3.7.

**Comment by lyy005** [comment]
I downgraded my pandas version from 2.0.2 to 1.5.3 and it runs smoothly now. 
`conda create -n hicexplorer_v3.6c hicexplorer pandas=1.5 -c bioconda -c conda-forge`
