### ISSUE TITLE
hicDetectLoops 'neihgborhood_unsmoothed' is not defined

### ISSUE THREAD

**Issue by Matheo-LESNE** [deeptools/HiCExplorer#860]
Hello,

I got an error trying to use hicDetectLoops.

Command : 
``
python hicDetectLoops -m /NANO/Result/Matheo/MCF7/distiller/pipeline_output/MCF7_distiller.cool -o ~/results.bedgraph
``

HiCExplorer was installed using the latest version available on pip (version 2.2.1.1)
``
pip install hicexplorer 
``

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/Venvpython3.6/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicDetectLoops.py", line 595, in compute_loops
    pArgs.maxAllowedInteractionsSmallerOne)
  File "/opt/Venvpython3.6/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicDetectLoops.py", line 215, in compute_long_range_contacts
    pMeanDifferenceNeighborhoodPeak, pMaxAllowedInteractionsSmallerOne)
  File "/opt/Venvpython3.6/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicDetectLoops.py", line 349, in candidate_region_test
    neighborhood[i, :] = smoothInteractionValues(neihgborhood_unsmoothed[i, :], 5)
NameError: name 'neihgborhood_unsmoothed' is not defined
```

Is the latest pip version too old ? 

Thank you for your time

**Comment by joachimwolff** [comment]
Yes, version 2.2.1.1 is outdated, the current version is 3.7.3 and is available via conda.
