### ISSUE TITLE
hicDifferentialTAD TypeError

### ISSUE THREAD

**Issue by CriticalSci** [deeptools/HiCExplorer#863]
Hello, I'm having issues with `hicDifferentialTAD` for relatively large bin sizes. Domains are called with `hicFindTADs` without any problems. Sometimes it works, sometimes it doesn't. Seems to break for specific chromosome and bin size combinations.

- [x] Search whether this issue (or a similar issue) has been solved before using the search tab above. Link the previous issue if appropriate below.
Could be related to #725 

- [x] Paste your HiCExplorer version (`hicInfo --version`) and your python version (`python --version`) below. 
hicInfo 3.7.2
Python 3.10.12

- [x] Have you checked our documentation on [hicexplorer.readthedocs.io](https://hicexplorer.readthedocs.io)?
Yes

- [x] Do you use [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) to install HiCExplorer? 
Yes

- [x] Do you use the latest HiCExplorer release? 
Yes

- [x] Paste the full HiCExplorer command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).
```
hicDifferentialTAD --targetMatrix prod/trgt_50K_NormRefCorr.h5 \
    --controlMatrix prod/ctrl_50K_NormRefCorr.h5 \
    --tadDomains prod/50K/chr2/ctrl_KR_FDR1_DELTA1_domains.bed \
    --outFileNamePrefix prod/50K/chr2/ctrl_KR_FDR1_DELTA1_P5 \
    --pValue 0.05 \
    --mode all \
    --modeReject one \
    --threads 12
```

- [x] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).
```
ERROR:hicmatrix.HiCMatrix:Index error
Traceback (most recent call last):
  File "/opt/anaconda3/envs/hicexplorer23/lib/python3.10/site-packages/hicmatrix/HiCMatrix.py", line 271, in getRegionBinRange
    endbin = sorted(self.interval_trees[chrname][endpos:endpos + 1])[0].data
IndexError: list index out of range
ERROR:hicexplorer.hicDifferentialTAD:'NoneType' object is not subscriptableTraceback (most recent call last):
  File "/opt/anaconda3/envs/hicexplorer23/lib/python3.10/site-packages/hicexplorer/hicDifferentialTAD.py", line 170, in computeDifferentialTADs
    outer_left_boundary_index_control = hic_matrix_control_inter_tad.getRegionBinRange(str(chromosom), start, end)[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by CriticalSci** [comment]
UPDATE:

I believe the issue originates from an incompatibility between the output of `hicMergeMatrixBins` and the processing in `hicFindTADs` and/or `hicDifferentialTAD`.

My current workaround is to generate the alternate resolutions directly from `cooler` allowing me to omit the `hicMergeMatrixBins` step.

1. hicMergeMatrixBins (skip)
2. hicNormalize
3. hicAdjustMatrix
4. hicCorrectMatrix
5. hicFindTADs
6. hicDifferentialTAD
