### ISSUE TITLE
hicPCA " invalid literal" error message

### ISSUE THREAD

**Issue by erbon7** [deeptools/HiCExplorer#883]
Hi everyone,

I'm trying to use the hicPCA command but I get an error message:
```
$ hicPCA -m mat_160K_corrected.cool --outputFileName pca1.bw pca2.bw pca3.bw --format bigwig
Traceback (most recent call last):
  File "/env/cng/proj/LBA/scratch/eb/tools/anaconda3/envs/hic_explorer/bin/hicPCA", line 7, in <module>
    main()
  File "/env/cng/proj/LBA/scratch/eb/tools/anaconda3/envs/hic_explorer/lib/python3.8/site-packages/hicexplorer/hicPCA.py", line 318, in main
    eigenvectors_correlate = np.hstack((eigenvectors_correlate, eigs[:, int(id) - 1:int(id)]))
ValueError: invalid literal for int() with base 10: ' '
$ hicPCA --version
hicPCA 3.7.1
```

Any clue ?

Thx

**Comment by joachimwolff** [comment]
Please update to the latest release. Thank you.

**Comment by matteozoia4** [comment]
Dear erbon7,

I incur in the same Error, how did you manage to solve the issue ??

Kind regards,

MZ

**Comment by mano2991** [comment]
hicPCA -m 7dpi_normalised.h5 --outputFileName pca1.bedgraph pca2.bedgraph --format bedgraph -we 1 2 this worked for me.
