### ISSUE TITLE
hicPCA flip signs with rna-seq?

### ISSUE THREAD

**Issue by Naveen-Ahuja** [deeptools/HiCExplorer#892]
Hi,

I would like to know if it makes sense to use rnaseq bigwig file in hicpca to flip the signs. For example, choose extra track type --> Histone Mark --> Histone Mark type=active. Would this be appropriate as there isn't an explicit rnaseq option, only histone mark and gene density?

Thank you

**Comment by Naveen-Ahuja** [comment]
Just following up using a bigwig file gives this error on the hicexplorer web:

`Fatal error: Exit code 1 ()
Tool generated the following standard error:

Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/__hicexplorer@3.6/bin/hicPCA", line 7, in <module>
    main()
  File "/usr/local/tools/_conda/envs/__hicexplorer@3.6/lib/python3.8/site-packages/hicexplorer/hicPCA.py", line 337, in main
    vecs_list = correlateEigenvectorWithGeneTrack(ma, vecs_list, args.extraTrack)
  File "/usr/local/tools/_conda/envs/__hicexplorer@3.6/lib/python3.8/site-packages/hicexplorer/hicPCA.py", line 145, in correlateEigenvectorWithGeneTrack
    bed = ReadBed(file_h)
  File "/usr/local/tools/_conda/envs/__hicexplorer@3.6/lib/python3.8/site-packages/hicexplorer/readBed.py", line 35, in __init__
    fields = self.get_no_comment_line()
  File "/usr/local/tools/_conda/envs/__hicexplorer@3.6/lib/python3.8/site-packages/hicexplorer/readBed.py", line 69, in get_no_comment_line
    line = toString(line)
  File "/usr/local/tools/_conda/envs/__hicexplorer@3.6/lib/python3.8/site-packages/hicexplorer/utilities.py", line 539, in toString
    return s.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 1: ordinal not in range(128)`
