### ISSUE TITLE
About hicPCA error

### ISSUE THREAD

**Issue by HaoWangFighting** [deeptools/HiCExplorer#898]
Hi ,

I'm experiencing an issue with hicPCA, where it gives a ValueError. I'm using python version 3.7.12 and hicexplorer version 3.7.2. Here is the command I run:
hicPCA --matrix CX6_200000.h5 --whichEigenvectors 1 --outputFileName CX6.200k.hicpca.bedgraph --format bedgraph --extraTrack gene.bed --pearsonMatrix CX6.200k.hicpca.pm --obsexpMatrix CX6.200k.hicpca.oem

The error as Traceback (most recent call last):
  File "/home/wanghao/miniconda3/envs/hicexplorer/bin/hicPCA", line 7, in <module>
    main()
  File "/home/wanghao/miniconda3/envs/hicexplorer/lib/python3.8/site-packages/hicexplorer/hicPCA.py", line 355, in main
    vecs_list = correlateEigenvectorWithGeneTrack(ma, vecs_list, args.extraTrack)
  File "/home/wanghao/miniconda3/envs/hicexplorer/lib/python3.8/site-packages/hicexplorer/hicPCA.py", line 190, in correlateEigenvectorWithGeneTrack
    _correlation = pearsonr(np.array(eigenvector[bin_id[0]:bin_id[1]]).real,
  File "/home/wanghao/miniconda3/envs/hicexplorer/lib/python3.8/site-packages/scipy/stats/_stats_py.py", line 4411, in pearsonr
    raise ValueError('x and y must have length at least 2.')
ValueError: x and y must have length at least 2.
How should I solve this problem? 
Thanks
![image](https://github.com/deeptools/HiCExplorer/assets/106525492/010c0ee3-578c-47ae-8aa6-f3ac0592851d)

**Welcome to the HiCExplorer GitHub repository!**

If your issue concern `HiCPlotTADs`, please post your issue to the [pyGenomeTracks github repo](https://github.com/deeptools/pyGenomeTracks/issues/new/choose).

**Before opening the issue please check
 that the following requirements are met :**

- [ ] Search whether this issue (or a similar issue) has been solved before using the search tab above. Link the previous issue if appropriate below.

- [ ] Paste your HiCExplorer version (`hicInfo --version`) and your python version (`python --version`) below. 
- [ ] Have you checked our documentation on [hicexplorer.readthedocs.io](https://hicexplorer.readthedocs.io)?
- [ ] Do you use [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) to install HiCExplorer? 
- [ ] Do you use the latest HiCExplorer release? If not, please install it via a conda environment: 
       `conda create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge`
       and activate the environment: `conda activate hicexplorer`.  Retry your command. You can exit a conda environment via `conda deactivate`. To learn more about conda and environments, please consider the following [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#).

Retry your command, is it solved now? If not please continue with the following:
- [ ] Paste the full HiCExplorer command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

- [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

**Comment by shRDJr** [comment]
Hello, I also encountered the same mistake, how did you solve it later?
