### ISSUE TITLE
No module named 'hic2cool'

### ISSUE THREAD

**Issue by sanjin725** [deeptools/HiCExplorer#903]
when I install by gitclone，and try hicConvertFormat -h have this error，
Traceback (most recent call last):
  File "/gpfs/home/pxx/soft/anaconda3/bin/hicConvertFormat", line 4, in <module>
    from hicexplorer.hicConvertFormat import main
  File "/gpfs/home/pxx/soft/anaconda3/lib/python3.11/site-packages/hicexplorer/hicConvertFormat.py", line 8, in <module>
    from hic2cool import hic2cool_convert
ModuleNotFoundError: No module named 'hic2cool'

**Comment by joachimwolff** [comment]
Have you installed the dependencies as listed in requirements.txt?
