### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by mw18f** [deeptools/HiCExplorer#910]
Hi, When I am running hicDetectLoops it occurs this error.
ERROR:hicexplorer.hicDetectLoops:The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()Traceback (most recent call last):
  File "/home/miao/miniconda3/envs/hicexplorer/lib/python3.10/site-packages/hicexplorer/hicDetectLoops.py", line 900, in compute_loops
    candidates, pValueList = compute_long_range_contacts(pHiCMatrix,
  File "/home/miao/miniconda3/envs/hicexplorer/lib/python3.10/site-packages/hicexplorer/hicDetectLoops.py", line 368, in compute_long_range_contacts
    candidates, _ = neighborhood_merge(
  File "/home/miao/miniconda3/envs/hicexplorer/lib/python3.10/site-packages/hicexplorer/hicDetectLoops.py", line 479, in neighborhood_merge
    if 'Fail: ' in new_candidate_list_threads[i]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I use conda to install hicexplorer, and version is 3.7.2. Python version is 3.10.13.  Thanks.

**Comment by joachimwolff** [comment]
Please use the current 3.7.5 release.
